// 🦆 Duck Rescue — Community-Mitglieder (Spiel-Daten)
// Quelle: plan/mitglieder.md. DSGVO-schonend: nur Vorname (+ ggf. Initial) + Rolle.
// Jedes Mitglied wird zu einer Ente; Name schwebt überm Kopf, Rolle erscheint im Endscreen.

const MEMBERS = [
  { name: "Max", rolle: "selbstständig, baut Websites" },
  { name: "Julian", rolle: "Assistenzarzt (Orthopädie)" },
  { name: "Tobias", rolle: "Bilanzbuchhalter" },
  { name: "Chris", rolle: "Baufirma, Prozessoptimierung" },
  { name: "Flo", rolle: "Student/IT, Startup-Gründung" },
  { name: "Lars", rolle: "Vollblut-Macher" },
  { name: "Jannes", rolle: "KI-Consulting-Agentur" },
  { name: "Calvin", rolle: "Industriekaufmann, KI-Automatisierung" },
  { name: "Jonah", rolle: "Webdesigner / Webflow-Entwickler" },
  { name: "Malte", rolle: "KI-Enthusiast" },
  { name: "Lukas", rolle: "digitale Baugenehmigung, baut Apps & Skills" },
  { name: "Aaron", rolle: "Digital-Marketing-Student, Marketing" },
  { name: "Mathias", rolle: "Haustechniker" },
  { name: "Peter", rolle: "Geschäftsführer Netzwerktechnik" },
  { name: "Sebastian S.", rolle: "Entwickler (20+ Jahre)" },
  { name: "Janine", rolle: "Marketing Managerin" },
  { name: "Friederike", rolle: "Onlineshop-Inhaberin" },
  { name: "Sophy", rolle: "Agent Builderin" },
  { name: "Cedric", rolle: "Inhaber Umzugsservice" },
  { name: "Marius", rolle: "Consulting, KI-Automation" },
  { name: "Lukas P.", rolle: "selbstständig, KI-Automatisierungen" },
  { name: "Gregor", rolle: "Macher" },
  { name: "Mario", rolle: "SAP-Consultant (AI & Engineering)" },
  { name: "Jan", rolle: "baut eine Social-/Event-App" },
  { name: "Jonny", rolle: "Projektleiter (Automatisierung)" },
  { name: "Markus", rolle: "Unternehmer" },
  { name: "Friederike Z.", rolle: "Onlineshop (Gesundheit)" },
  { name: "Philipp", rolle: "Head of Finance & IT" },
  { name: "Malte P.", rolle: "AI-Student, AI Agents" },
  { name: "Ben", rolle: "KI-Student" },
  { name: "Rishav", rolle: "baut eigene Claude-Projekte" },
  { name: "Selina", rolle: "Podcast-Host, baut Tools" },
  { name: "Mila", rolle: "Finanz-Enthusiastin" },
  { name: "Marcel", rolle: "Automatisierung im Unternehmen" },
  { name: "Vloh", rolle: "Gründer Marketingagentur" },
  { name: "Bartl", rolle: "AI Automation Spezialist" },
  { name: "Till", rolle: "Reporting / Workforce Management" },
  { name: "Wolfgang", rolle: "Unternehmer (Datenschutz/Compliance)" },
  { name: "Husnain", rolle: "Gründung KI-Consulting" },
  { name: "Mika", rolle: "Zeichner (Ingenieurbau), baut Tools" },
  { name: "Gustav", rolle: "Crypto/Fintech, Maschinenbau-Student" },
  { name: "Christian", rolle: "Gewerbeimmobilien-Berater" },
  { name: "Fabian", rolle: "Software Sales, baut Fitness-App" },
  { name: "Sascha", rolle: "IT-Service (Bankenumfeld)" },
  { name: "Olli", rolle: "selbstständig, Automatisierung" },
  { name: "Axel", rolle: "Apotheker & Heilpraktiker" },
  { name: "Simon", rolle: "Berater" },
  { name: "Tarik", rolle: "Ingenieurbüro" },
  { name: "Monique", rolle: "Online-Programm" },
  { name: "Rene", rolle: "Enterprise Architect & Coach" },
  { name: "Harald", rolle: "selbstständig, B2B-Automatisierung" },
  { name: "Thomas", rolle: "Automotive, KI-Prozesse" },
  { name: "Martin", rolle: "Projekt-Terminplanung" },
  { name: "Axel M.", rolle: "Jurist, Tools für Arztpraxen" },
  { name: "Hawk", rolle: "Innovation Manager" },
  { name: "Niko", rolle: "Content (Sales/Selfimprovement)" },
  { name: "Fabian F.", rolle: "Amazon-Bücher, Automatisierung" },
  { name: "Sascha S.", rolle: "Unternehmer & Macher" },
  { name: "Steven", rolle: "Hochzeitsfotograf & Creator" },
  { name: "Connor", rolle: "Sanitätshaus, Automatisierung" },
  { name: "Tim", rolle: "baut eigene Unternehmenssoftware" },
  { name: "Nyko", rolle: "Beamtenanwärter, App-Entwicklung" },
  { name: "Patric", rolle: "Gastronomie, baut Mitarbeiter-App" },
  { name: "Matthias", rolle: "Senior Account Executive (Sales)" },
  { name: "Emre", rolle: "KI-Automatisierungs-Agentur" },
  { name: "Christian L.", rolle: "Gesundheitsbranche" },
  { name: "Toni", rolle: "KI-Lösungen für Unternehmen" },
  { name: "Dom", rolle: "Sicherheitsdienst, Abläufe optimieren" },
  { name: "Malte S.", rolle: "baut eine Beziehungs-App" },
  { name: "Gianmarco", rolle: "KI/Automatisierung, Assistenz" },
  { name: "Marco", rolle: "Gründer (GPS-Telemetrie-Apps)" },
  { name: "Rika", rolle: "baut Onlinebusiness mit KI" },
  { name: "Sebastian V.", rolle: "KI-Anwender, lernt Claude" },
  { name: "Isabella", rolle: "Personal Brand, Karussells/Workflows" },
  { name: "Robin", rolle: "Marketing-Agentur, baut Apps" },
  { name: "Andreas", rolle: "Agentic Work, Automationen, Trading" },
  { name: "Robin D.", rolle: "Maschinenbau, persönlicher Assistent" },
  { name: "Jan A.", rolle: "Student, Nebenverdienst mit KI" },
  { name: "Christoph", rolle: "KI im Business, Agentic OS" },
  { name: "David", rolle: "Abiturient, KI-Automationen" },
  { name: "Noah", rolle: "Online-Coaching (Fitness)" },
  { name: "Holger", rolle: "Coach/Trainer, Marketing-Automatisierung" },
  { name: "Nadine", rolle: "Finance & Operations, Automatisierung" },
  { name: "Robin W.", rolle: "Nebengewerbe, Shop/SEO" },
  { name: "Tom", rolle: "Skitrainer & Canyoning-Guide" },
  { name: "Leon", rolle: "Gebietsvertriebsleiter (Maschinenbau)" },
  { name: "Tino", rolle: "Profi-Eishockey, Performance-HUB" },
  { name: "Marc", rolle: "Erzieher / Medienpädagoge" },
  { name: "Robin S.", rolle: "Jira/Salesforce-PM, baut App" },
  { name: "Lorenz", rolle: "Bio-Landwirt & Projektmanager" },
  { name: "Isabelle", rolle: "Media Buyer (Ads) & Social Media" },
  { name: "Karsten", rolle: "KI-begeistert, sucht den roten Faden" },
  { name: "Elmar", rolle: "KI-Consultant, Automationen" },
  { name: "Sebastian K.", rolle: "eCom, baut Software-Plug-in" },
  { name: "Robin K.", rolle: "Sysadmin, KI-Implementierung" },
  { name: "Diane", rolle: "neugierige Einsteigerin" },
];
